### PR TITLE
Added some basic handling for money types.

### PR DESCRIPTION
**Pull request by elliotcourant**
When a dollar sign is present when parsing a float value the dollar sign
will now be removed. Previously it was causing an error to be returned
from strconv.ParseFloat.

This should resolve: https://github.com/go-pg/pg/issues/1074

### CODE REVIEW

**Comment by vmihailenco** [comment]
This only works for '$' - what should we do for all the other currencies?

**Comment by elliotcourant** [comment]
It looks like the currency symbol used is based on `lc_monetary`, I'll do some research and see if there is an easy way to handle that. 

I could just make a map of the currency symbols and have those symbols removed, but that seems very inefficient.

**Comment by elliotcourant** [comment]
It might be more difficult than simply replacing some characters.
The following query is very simple and returns a result that could be easily parsed.

> ```sql
> SET lc_monetary TO 'EN_ie';
> SELECT 5.5::money;
> ```
> ```
> €5.50
> ```

But if we are using Russian currency it gets a lot more complicated.
> ```sql
> SET lc_monetary TO 'RU_ru';
> SELECT 5.5::money;
> ```
> ```
> 5,50 руб.
> ```

I think the best approach would be to detect the type returned from PostgreSQL using the OID and then if it is money; parse the value to a float using Regex. That way there is only overhead when actually using money types.

**Comment by elliotcourant** [comment]
So after some more research, I've found a way to get `lc_monetary` information in Go by calling some C functions with cgo. Using `locale.h` should work on all platforms as well. I believe I can build something to parse anything returned from PostgreSQL in any format, but it would need to know the locale that Postgres is using. 

I will build out a function to do the parsing and post it here for you to take a look at, if you think that it will work and not cause problems then I can implement it into your library.

**Comment by ORBAT** [comment]
As a go-pg user, I'm not really thrilled about extra the cgo dependency just to parse things related to monetary types, plus I'd assume it'd make maintenance of the package itself harder. 

Have you taken a look at the packages under https://godoc.org/golang.org/x/text, such as https://godoc.org/golang.org/x/text/language and https://godoc.org/golang.org/x/text/currency? It seems like they could help here, in combination with eg. https://github.com/cloudfoundry-attic/jibber_jabber to get the system locale in a platform-independent, pure Go way

**Comment by ECourant** [comment]
I will look into those and see if I can make a pure go version. I agree a cgo dependency is a bit extreme. Essentially I just need the information from `lc_monetary`, if there is a pure go way to get that then that would be 110% ideal.

**Comment by elliotcourant** [comment]
@ORBAT After doing some more research on the resources you mentioned and some other documentation I was able to dig up. I think I figured out a way. I'm going to make a separate (pure-go) package specifically for handling/parsing monetary values without cgo. Then I'll build a wrapper for that into go-pg/pg, this way it will be easier to maintain and the money parsing can be used as a standalone library.

**Comment by elliotcourant** [comment]
Quick update.

I've finished creating a pure-go library for parsing and formatting monetary values. I will be redoing all my work in this PR over the next few days to get this implemented. Current the package supports ~200 different locales.

https://github.com/elliotcourant/gomonetary

**Comment by elliotcourant** [comment]
I'm gonna close this MR for now, I haven't heard from the guys who wanted it. And I'm running into some complexities. I'll reopen if it becomes relevant again.

**Pull request closed without merging**
