### PR TITLE
types: implement values operator

### PR DESCRIPTION
**Pull request by siteshen**

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can you add an example how this is going to be used?

**Comment by siteshen** [comment]
@vmihailenco I need to fetch rows by composite keys like this, and it's tedious and error-prone to concat sql:
```sql
SELECT * FROM "storages" WHERE ((type, name) IN (VALUES ('sql','postgres'), ('nosql','redis')));
```
And i wrote a runnable demo:
```go
package main

import (
	"github.com/go-pg/pg"
	"github.com/go-pg/pg/orm"
	"github.com/go-pg/pg/types"
)

type Storage struct {
	Type string
	Name string
}

func main() {
	// shell: createdb demo
	db := pg.Connect(&pg.Options{
		Database: "demo",
		User:     "",
	})

	if err := db.CreateTable(&Storage{}, &orm.CreateTableOptions{IfNotExists: true}); err != nil {
		panic(err)
	}

	storages := []*Storage{}
	if err := db.Model(&storages).WhereIn("(type, name) IN (?)", types.Values([]interface{}{
		[]string{"sql", "postgres"},
		[]string{"nosql", "redis"},
	})).Select(); err != nil {
		panic(err)
	}
	// sample output:
	// SELECT * FROM "storages" AS "storage" WHERE ((type, name) IN (VALUES ('sql','postgres'), ('nosql','redis')));
}

```

**Comment by vmihailenco** [comment]
Please update go-pg and try following:

```
	err := db.Model(&storages).
		WhereIn("(type, name) IN (?)",
			[]string{"sql", "postgres"},
			[]string{"nosql", "redis"}).
		Select()
```

It should do the same with more concise syntax/API.

**Comment by siteshen** [comment]
Thanks, it works.

**Pull request closed without merging**
