### PR TITLE
Format order with params

### LINKED ISSUE #902: Cannot use TableAlias in .Order()
`.Order("?TableAlias.id")` doesn't substitute alias in place of ?TableAlias.
`.OrderExpr("?TableAlias.id")` works just fine but I believe they both should format query with param substitutions.

### PR DESCRIPTION
**Pull request by 23doors**
fixes #902

### CODE REVIEW

**Comment by 23doors** [comment]
@vmihailenco  I just started using go-pg recently so I'm not sure if this approach is completely ok. Correct me if I'm wrong.

**Comment by vmihailenco** [comment]
Why not to use `OrderExpr`? `Order` is supposed to be as strict as possible so you can feed it any string and it produces safe SQL.

**Comment by 23doors** [comment]
Sure, OrderExpr works but it just seems that param evaluation should be standard behavior. At least for such basic param like ?TableAlias which is the only way to avoid having ambigous columns in multi-table queries. 

It’s just strange to me and it’s nor exactly anywhere in docs that params works in Where() but not in Order().

**Comment by 23doors** [comment]
But I think I see what you're getting at. Maybe consider merging .Order() and .OrderExpr()? Or add a note to .Order() and .Columns() that params are not evaluated there?

**Comment by vmihailenco** [comment]
Yeah, I guess we need a note. Do you care to send a PR? :)

**Comment by 23doors** [comment]
#912

**Pull request closed without merging**
