### PR TITLE
Feature/sasl

### PR DESCRIPTION
**Pull request by vmihailenco**
Fixes https://github.com/go-pg/pg/issues/960

### CODE REVIEW

**Comment by niski84** [comment]
Hi this is wonderful @vmihailenco   Thank you for the prompt feature.    The GA release is in late Sept.  Will this feature be merged by then?

**Comment by vmihailenco** [comment]
This is blocked by https://bitbucket.org/mellium/sasl/issues/8/base64-encoding-of-challenge-and-response. If it is not fixed I will have to find another SASL client.

**Comment by niski84** [comment]
@vmihailenco  thank you!

**Comment by SamWhited** [comment]
Hi all, sorry I missed the issue on my repo, apparently I wasn't subscribed to all issues and didn't get an email (fixed now). If you'd like to reach out (here or on Bitbucket), I'd be curious what postgresql is doing since base64 is part of the SASL spec. Thanks, and sorry I missed your comment for so long!

/cc @vmihailenco

**Comment by vmihailenco** [comment]
Thanks for reaching out - I've tried to reply at at https://bitbucket.org/mellium/sasl/issues/8/base64-encoding-of-challenge-and-response - let's continue discussion there.

**Pull request merged**
